"""add castling columns

Revision ID: f9d1a4cfce16
Revises: 620ade976de2
Create Date: 2023-10-16 10:19:26.916634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9d1a4cfce16'
down_revision = '620ade976de2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_board', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('white_long_ok', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('white_short_ok', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('black_long_ok', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('black_short_ok', sa.Boolean(), nullable=False))
        batch_op.drop_column('board_state')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('board_state', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('black_short_ok')
        batch_op.drop_column('black_long_ok')
        batch_op.drop_column('white_short_ok')
        batch_op.drop_column('white_long_ok')
        batch_op.drop_column('_board')

    # ### end Alembic commands ###