"""add game table

Revision ID: 3e0aa30ed230
Revises: ffdc0a98111c
Create Date: 2023-08-18 17:35:20.473772

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = '3e0aa30ed230'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('code', sa.String(length=12), nullable=False),
                    sa.Column('board_state', sa.String(
                        length=255), nullable=False),
                    sa.Column('white_id', sa.Integer(), nullable=True),
                    sa.Column('black_id', sa.Integer(), nullable=True),
                    sa.Column('completed', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['black_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['white_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('code')
                    )

    if environment == "production":
        op.execute(f"ALTER TABLE games SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    # ### end Alembic commands ###
