"""index for random string

Revision ID: d4fe5356ab4e
Revises: f9d1a4cfce16
Create Date: 2023-12-14 13:00:39.683068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4fe5356ab4e'
down_revision = 'f9d1a4cfce16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_constraint('games_code_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_games_code'), ['code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_games_code'))
        batch_op.create_unique_constraint('games_code_key', ['code'])

    # ### end Alembic commands ###