"""rename castling columns

Revision ID: 54c7df800e03
Revises: d4fe5356ab4e
Create Date: 2024-01-17 16:13:12.050768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54c7df800e03'
down_revision = 'd4fe5356ab4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('white_can_long', sa.Boolean()))
        batch_op.add_column(sa.Column('white_can_short', sa.Boolean()))
        batch_op.add_column(sa.Column('black_can_long', sa.Boolean()))
        batch_op.add_column(sa.Column('black_can_short', sa.Boolean()))
        batch_op.drop_column('white_short_ok')
        batch_op.drop_column('black_long_ok')
        batch_op.drop_column('black_short_ok')
        batch_op.drop_column('white_long_ok')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('white_long_ok', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(
            sa.Column('black_short_ok', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(
            sa.Column('black_long_ok', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(
            sa.Column('white_short_ok', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('black_can_short')
        batch_op.drop_column('black_can_long')
        batch_op.drop_column('white_can_short')
        batch_op.drop_column('white_can_long')

    # ### end Alembic commands ###
