"""add nullable to EP

Revision ID: cbe943c38178
Revises: 87e87e2f0f20
Create Date: 2024-03-20 20:59:35.259140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbe943c38178'
down_revision = '87e87e2f0f20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.alter_column('en_passant',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.alter_column('en_passant',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)

    # ### end Alembic commands ###